name: Java CI with Maven and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven (tests inclus)
        run: mvn -B clean verify
        working-directory: ./backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=EvannLietard_Erp -Dsonar.organization=erp-backend
        working-directory: ./backend

      - name: Build Docker image
        run: docker build -t erp .
        working-directory: ./backend

      - name: Debug MongoDB URI in container
        run: docker run -e MONGODB_URI=${{ secrets.MONGODB_URI }} erp sh -c 'echo $MONGODB_URI'

      - name: Run container with MongoDB URI secret
        run: docker run -e MONGODB_URI=${{ secrets.MONGODB_URI }} -p 8080:8080 erp

      - name: Show Docker logs
        run: docker logs $(docker ps -alq)